jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rails_blogapp_test
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v4 

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: latest
          bundler-cache: true
          ruby-version: .ruby-version

      - name: Set Rails Master Key  
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: echo "$RAILS_MASTER_KEY" > config/master.key

      - name: Remove vendor directory if necessary
        run: rm -rf vendor

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -qq libvips
          bundle install

      - name: Standardrb Check
        run: bundle exec standardrb

      - name: ERB Lint
        run: bundle exec erblint --lint-all

      - name: Brakeman Check
        run: bundle exec brakeman
        
      - name: Run rspec
        run: bundle exec rspec
