name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: rails_blogapp_test
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: latest 
          bundler-cache: true
          ruby-version: .ruby-version

      - name: Disable error_highlight
        run: echo "RUBYOPT='--disable-error_highlight'" >> $GITHUB_ENV

      - name: Remove vendor directory if necessary
        run: rm -rf vendor

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y -qq libvips
          bundle install

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 1
          done

      - name: Set up database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:create db:schema:load

      - name: Standardrb Check
        run: bundle exec standardrb

      - name: ERB Lint
        run: bundle exec erblint --lint-all

      - name: Brakeman Check
        run: bundle exec brakeman

      - name: Run RSpec Tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec
